import { CLOSE_STAGE_IDS, type CloseStageId } from '@/domains/financial_period/schemas';

export const CLOSE_STAGE_LABELS: Record<CloseStageId, string> = {
  ACCOUNT_BALANCE: '帳戶餘額',
  TRANSACTION_VALIDATION: '交易驗證',
  SECURITIES_TRADE: '證券買入／賣出',
  PORTFOLIO_CASH_FLOW: 'Portfolio 金流',
  PROJECT_SETTLEMENT: '專案結算',
  DEBT_REPAYMENT: '債務還款',
  COMPLETENESS_CHECK: 'Completeness Check',
  FINANCIAL_REPORTS: 'Financial Reports',
  CLOSE_PERIOD: 'Close Period',
};

export const getCloseStageLabel = (stageId: CloseStageId): string =>
  CLOSE_STAGE_LABELS[stageId] ?? stageId;

export const CLOSE_STAGE_ORDER: readonly CloseStageId[] = CLOSE_STAGE_IDS;

export const MONTHLY_CLOSE_LABELS = {
  PAGE_TITLE: '月度關帳',
  PAGE_SUBTITLE: 'MONTHLY CLOSE WORKFLOW',
  START: '開始關帳',
  BUY: '買入',
  SELL: '賣出',
  SHAREHOLDER_FINANCING: '股東融資',
  DIVIDEND_PAYOUT: '發放分紅',
  DEPOSIT: '存入',
  WITHDRAW: '領出',
  STARTED: '關帳進行中',
  CONTINUE: 'CONTINUE →',
  RECONFIRM: '階段已完成',
  RECONFIRM_ACTION: '重新確認，繼續關帳',
  REVIEWING: 'REVIEWING',
  BACK_TO_CURRENT: '返回當前步驟',
  RESOLVE_REVIEW: '審閱完畢，繼續關帳',
  FINALIZED: '本期已完成關帳',
  FINALIZED_SUBTITLE: 'FINALIZED',
  PAUSED: '已暫停，待審閱',
  NEEDS_REVIEW: 'NEEDS REVIEW',
  NEEDS_RECONFIRM: 'NEEDS RECONFIRM',
  REOPENED_TITLE: '此期間已經關帳',
  REOPENED_CONTEXT: '已關帳的期間重新開啟後，財務報表與關帳決定會被撤回，需重新產生報表並重新關帳。',
  REOPENED_CONSEQUENCE: '此期間之後所有已關帳的期間也會改為待審閱（NEEDS REVIEW）。',
  REOPEN_CONFIRM: '重新開啟',
  REOPENED_BANNER: '前期關帳已重新開啟，此期間需重新審閱並重新關帳',
  CASCADE_BANNER: '此期間已改為待審閱：前期關帳已重新開啟',
  SHOW_WORKFLOW: 'SHOW WORKFLOW',
  HIDE_WORKFLOW: 'HIDE WORKFLOW',
  CLOSED: 'CLOSED',
  IN_PROGRESS: 'IN PROGRESS',
  OPEN: 'OPEN',
  NOT_STARTED: 'NOT STARTED',
  PERIOD_LABEL: '關帳期間',
  EVIDENCE_LABEL: '階段證據',
  INPUTS_LABEL: '階段輸入',
  NO_DATA: '-',
  NO_EVIDENCE: '尚無階段證據。',
  STAGE_GUIDANCE: '階段順序僅為引導，可依需求調整確認順序。',
  LOADING: '載入中...',
  LOAD_ERROR: '無法載入關帳狀態。',
  CONFIRM_ERROR: '確認失敗，請稍後再試。',
  START_ERROR: '無法開始關帳。',
  REOPEN_ERROR: '無法重新開啟關帳。',
  SELECT_PERIOD: '選擇關帳期間',
  READY: '就緒',
  NOT_READY: '未就緒',
  PERSISTED: '已產生',
  NOT_PERSISTED: '尚未產生',
  ZERO_ACTIVITY: '零活動',
  TRANSACTION_ISSUES: '交易驗證問題',
  ADJUSTMENT: '現金流調整',
  REPORTS_PERSISTENCE: '報表產生狀態',
} as const;
