import { CLOSE_STAGE_IDS, type CloseStageId } from '@/domains/financial_period/schemas';

export const CLOSE_STAGE_LABELS: Record<CloseStageId, string> = {
  ACCOUNT_BALANCE: '帳戶餘額',
  TRANSACTION_VALIDATION: '交易驗證',
  SECURITIES_TRADE: '證券買入／賣出',
  PORTFOLIO_CASH_FLOW: 'Portfolio 金流',
  PROJECT_SETTLEMENT: '專案結算',
  DEBT_REPAYMENT: '債務還款',
  COMPLETENESS_CHECK: 'Completeness Check',
  FINANCIAL_REPORTS: 'Financial Reports',
  CLOSE_PERIOD: 'Close Period',
};

export const getCloseStageLabel = (stageId: CloseStageId): string =>
  CLOSE_STAGE_LABELS[stageId] ?? stageId;

export const CLOSE_STAGE_ORDER: readonly CloseStageId[] = CLOSE_STAGE_IDS;

export const MONTHLY_CLOSE_LABELS = {
  PAGE_TITLE: '月度關帳',
  PAGE_SUBTITLE: 'MONTHLY CLOSE WORKFLOW',
  START: '開始關帳',
  BUY: '買入',
  SELL: '賣出',
  SHAREHOLDER_FINANCING: '股東融資',
  DIVIDEND_PAYOUT: '發放分紅',
  SECURITIES_TRANSACTIONS: '證券交易紀錄',
  FINANCING_RECORDS: '融資紀錄',
  ADD_TRANSACTION: '新增交易',
  ADD_SECURITIES_TRANSACTION: 'ADD SECURITIES TRANSACTION',
  ADD_FINANCING_TRANSACTION: 'ADD FINANCING TRANSACTION',
  TYPE: 'Type',
  AMOUNT: 'Amount',
  DESCRIPTION: 'Description',
  PROJECT: 'Project',
  NO_PROJECT: '— 無 —',
  DRAWER_CANCEL: 'CANCEL',
  DRAWER_ADD: 'ADD',
  DRAWER_DELETE: 'DELETE',
  TRANSACTIONS_COUNT: 'transactions',
  NET_INVESTMENT_CASH_FLOW: 'NET INVESTMENT CASH FLOW',
  NET_FINANCING_CASH_FLOW: 'NET FINANCING CASH FLOW',
  PORTFOLIO_BALANCE: 'PORTFOLIO BALANCE',
  FROM_ACCOUNT: 'FROM ACCOUNT',
  SECURITIES_BALANCE: '證券餘額',
  BANK_BALANCE: '銀行餘額',
  MONTHLY_CASH_FLOW: 'MONTHLY CASH FLOW',
  CASH_IN: 'CASH IN',
  CASH_OUT: 'CASH OUT',
  NET_CASH_FLOW: 'NET CASH FLOW',
  MONTHLY_RETURN: 'MONTHLY RETURN',
  RETURN_RATE: '報酬率',
  RETURN: '報酬',
  TOTAL_RETURN: '本期合計報酬',
  EDIT_TRANSACTION: 'EDIT TRANSACTION',
  NO_TRANSACTIONS: '尚無紀錄',
  NO_PROJECTS: '沒有專案',
  UNSETTLED: '尚未結算',
  DEPOSIT: '存入',
  WITHDRAW: '領出',
  STARTED: '關帳進行中',
  CONTINUE: 'CONTINUE →',
  RECONFIRM: '階段已完成',
  RECONFIRM_ACTION: '重新確認，繼續關帳',
  EMPTY_STAGE_WARNING_TITLE: '目前沒有任何交易紀錄',
  EMPTY_STAGE_WARNING_CONTEXT: '證券交易紀錄與融資紀錄都是空的。',
  EMPTY_STAGE_WARNING_CONSEQUENCE: '仍然要確認這個階段嗎?',
  REVIEWING: 'REVIEWING',
  BACK_TO_CURRENT: '返回當前步驟',
  RESOLVE_REVIEW: '審閱完畢，繼續關帳',
  FINALIZED: '本期已完成關帳',
  FINALIZED_SUBTITLE: 'FINALIZED',
  PAUSED: '已暫停，待審閱',
  NEEDS_REVIEW: 'NEEDS REVIEW',
  NEEDS_RECONFIRM: 'NEEDS RECONFIRM',
  REOPENED_TITLE: '此期間已經關帳',
  REOPENED_CONTEXT:
    '已關帳的期間重新開啟後，關帳決定會被撤回；既有報表保留作為比對基準，需重新檢視並重新產生報表後才能重新關帳。',
  REOPENED_CONSEQUENCE: '此期間之後所有已關帳的期間也會改為待審閱（NEEDS REVIEW）。',
  REOPEN_CONFIRM: '重新開啟',
  CANCEL: 'CANCEL',
  REOPENED_BANNER: '前期關帳已重新開啟，此期間需重新審閱並重新關帳',
  CASCADE_BANNER: '此期間已改為待審閱：前期關帳已重新開啟',
  GO_TO_RESET_TITLE: '此步驟之後的確認將重新進入待確認',
  GO_TO_RESET_CONSEQUENCE: '步驟 {range} 將重新進入待確認，報表需重新產生。',
  GO_TO_RESET_CONFIRM: '重新確認步驟',
  WALK_GUIDANCE: '已暫停：請按步驟順序一一確認，無法跳回後面的步驟。',
  SHOW_WORKFLOW: 'SHOW WORKFLOW',
  HIDE_WORKFLOW: 'HIDE WORKFLOW',
  CLOSED: 'CLOSED',
  IN_PROGRESS: 'IN PROGRESS',
  OPEN: 'OPEN',
  NOT_STARTED: 'NOT STARTED',
  PERIOD_LABEL: '關帳期間',
  EVIDENCE_LABEL: '階段證據',
  INPUTS_LABEL: '階段輸入',
  NO_DATA: '-',
  NO_EVIDENCE: '尚無階段證據。',
  STAGE_GUIDANCE: '階段順序僅為引導，可依需求調整確認順序。',
  LOADING: '載入中...',
  LOAD_ERROR: '無法載入關帳狀態。',
  CONFIRM_ERROR: '確認失敗，請稍後再試。',
  STAGE_ALREADY_COMPLETED_ERROR: '此階段已完成確認，無法重新確認。',
  START_ERROR: '無法開始關帳。',
  REOPEN_ERROR: '無法重新開啟關帳。',
  SELECT_PERIOD: '選擇關帳期間',
  SWITCH_PERIOD: '切換期間',
  READY: '就緒',
  NOT_READY: '未就緒',
  PERSISTED: '已產生',
  NOT_PERSISTED: '尚未產生',
  PERSISTENCE_UNKNOWN: '狀態未知',
  ZERO_ACTIVITY: '零活動',
  TRANSACTION_ISSUES: '交易驗證問題',
  ADJUSTMENT: '現金流調整',
  REPORTS_PERSISTENCE: '報表產生狀態',
  INTEREST_RATE: '年利率',
  PREVIOUS_BALANCE: '期初餘額',
  TOTAL_PAYMENT: '總繳款',
  PRINCIPAL: '本金',
  INTEREST: '利息',
  MONTHLY_DUE: '應繳',
  CLOSING_BALANCE: '期末餘額',
  DEBT_TOTAL: '債務合計',
  FINANCIAL_REPORTS_TITLE: '財務報表',
  FINANCIAL_REPORTS_NOTE: '損益表、資產負債表與現金流量表',
  INCOME_SECTION: '收入',
  EXPENSE_SECTION: '支出',
  NET_INCOME: '本期淨利',
  ASSETS_SECTION: '資產',
  LIABILITIES_SECTION: '負債',
  EQUITY_SECTION: '權益',
  LIABILITIES_PLUS_EQUITY: '負債 + 權益',
  TOTAL_SUFFIX: '合計',
  INFLOW: '流入',
  OUTFLOW: '流出',
  NET_CASH_CHANGE: '現金淨變動',
  ACTUAL_BALANCE: '實際餘額',
  ADJUSTMENT_WARNING: '現金流調整超過 1,000，請先確認再產生報表。',
  READINESS_CHECK_TITLE: '就緒檢查',
  READINESS_CHECK_NOTE: '報表產生前，確認資料能否產生正確報表',
  READINESS_EXCEPTIONS: '例外項目',
  GO_TO_STAGE_PREFIX: 'GO TO ',
  GO_TO_STAGE_SUFFIX: ' →',
  SUMMARY_LABEL: 'CLOSE SUMMARY',
  SUMMARY_TITLE: '關帳總結',
  SUMMARY_ACTIVITY: '關帳活動',
  SUMMARY_FINANCIAL: '財務結果',
  SUMMARY_REPORTS: '產生報表',
  SUMMARY_CLOSE_ACTION: '正式關帳',
  SUMMARY_CLOSE_TITLE: '確認正式關帳',
  SUMMARY_CLOSE_CONTEXT: '關帳後此期間的報表與階段確認將固定為最終紀錄。',
  SUMMARY_CLOSE_CONSEQUENCE:
    '重開此期間會使其後所有已關帳期間轉為待審閱（NEEDS REVIEW），恢復須逐期手動處理。',
  GENERATE_REPORTS: 'GENERATE REPORTS',
  REPORTS_GENERATED: 'REPORTS GENERATED',
  GENERATED_AT: '產生時間',
  EXISTING_REPORTS_WARNING: '此期間已有先前產生的報表；確認後將以目前預覽重新產生並覆寫。',
  PERSISTENCE_UNKNOWN_WARNING: '無法確認報表是否已產生，暫時無法產生報表，請重新載入後再試。',
  DRIFT_BLOCK_MESSAGE: '步驟 8 的報表與已產生報表不一致，請先回到步驟 8 重新產生報表再關帳。',
  DRIFT_BLOCK_ACTION: '回到步驟 8',
  PREVIEW_ERROR: '無法載入報表預覽。',
} as const;
