export const RetirementExpenseDialogLabels = {
  editTitle: 'Edit Expense Category',
  createTitle: 'Add Expense Category',
  editDescription: 'Update the details of this expense category.',
  createDescription: 'Add a new expense category manually or import from the ledger.',
  addAction: 'Add Expense',
  nameLabel: 'Name',
  namePlaceholder: 'e.g., Groceries',
  currentAnnual: 'Current Annual ($)',
  retirementMultiplier: '退休後費用比例 (%)',
  endYearRequired: 'End Year',
  duration: 'Duration',
  lifelong: 'Lifelong',
  until: (endYear: string) => `Until ${endYear}`,
  growth: 'Growth',
  usingPlanInflation: (rate: number) => `Using plan inflation: ${rate}%`,
  growthPercent: (rate: number) => `${rate}% growth`,
  advanced: 'Advanced',
  growthRateLabel: 'Growth Rate (%)',
  startYear: 'Start Year',
  endYearOptional: 'End Year (Optional)',
  planInflation: (rate: number) => `Plan inflation ${rate}%`,
  planInflationPlaceholder: 'Plan inflation',
  savingAction: 'Saving...',
  saveChangesAction: 'Save Changes',
  debtDerivedHint: 'System-derived from debt repayment import.',
  lifelongPlaceholder: 'Lifelong',
  retirementYearPreview: (amount: number) =>
    `退休第一年支出約 ${Math.round(amount).toLocaleString()} /yr (估算)`,
} as const;
