export const RetirementIncomeDialogLabels = {
  editTitle: 'Edit Income Stream',
  createTitle: 'Add Income Stream',
  editDescription: 'Update the details of this income source.',
  createDescription: 'Add a new income source.',
  addAction: 'Add Income',
  nameLabel: 'Name',
  namePlaceholder: 'e.g., Salary',
  type: 'Type',
  typePlaceholder: 'Select type...',
  currentAnnual: 'Current Annual ($)',
  noCurrentAnnualMarker: '—',
  importHint: 'Import from Ledger to populate.',
  retirementAnnual: 'Retirement Annual (from retirement year)',
  growth: 'Growth',
  usingPlanInflation: (rate: number) => `Using plan inflation: ${rate}%`,
  growthPercent: (rate: number) => `${rate}% growth`,
  duration: 'Duration',
  lifelong: 'Lifelong',
  until: (endYear: string) => `Until ${endYear}`,
  lifelongLabel: 'Lifelong',
  retirementAnnualPlaceholder: '0 for no retirement income',
  advanced: 'Advanced',
  growthRateLabel: 'Growth Rate (%)',
  startYear: 'Start Year',
  endYear: 'End Year (Optional)',
  planInflation: (rate: number) => `Plan inflation ${rate}%`,
  planInflationPlaceholder: 'Plan inflation',
  lifelongPlaceholder: 'Lifelong',
  savingAction: 'Saving...',
  saveChangesAction: 'Save Changes',
} as const;
