export const TransactionCategoryLabels = {
  income: {
    salary: '薪水',
    bonus: '獎金',
    investment: '投資',
    refund: '退款回補',
    side_business: '副業',
    other: '其他收入',
  },
  expense: {
    food: '餐飲',
    transportation: '交通',
    shopping: '購物',
    entertainment: '娛樂',
    housing: '居住',
    rent: '房租',
    living: '生活',
    insurance: '保險',
    education: '教育',
    social: '人際',
    other: '其他支出',
  },
  investment: {
    investment: '買入證券',
    property: '買入不動產',
    cash: '投資現金流',
    other: '其他投資',
  },
  financing: {
    loan: '借貸',
    owner_investment: '股東融資',
    owner_draw: '發放分紅',
    initial_capital: '初始資金',
    cash: '融資現金流',
    other: '其他融資',
  },
} as const;
