export const DASHBOARD_STAT_ROW_LABELS = {
  SECTION_TITLE: 'FINANCIAL SNAPSHOT',
  TOTAL_ASSETS: '總資產',
  TOTAL_LIABILITIES: '總負債',
  MONTHLY_CASH_FLOW: '月現金流',
  PORTFOLIO_RETURN: '投資報酬率',
  INVESTMENT_LEVERAGE: '投資槓桿',
  ANCHOR_PREFIX: 'ANCHORED',
} as const;
